# Snakefile for running the pipeline.

rule all:
    input:
#        '../results/galaxy-ids/paste_manifest_out.txt',
#        '../results/galaxy-ids/import_out.txt',
#        '../results/galaxy-ids/dada2_out.txt',
#        '../results/galaxy-ids/mafft-raxml_out.txt',
#        '../results/galaxy-ids/rarefy_out.txt',
#        '../results/galaxy-ids/alpha_div_out.txt',
#        '../results/galaxy-ids/beta_div_out.txt',
#        '../results/galaxy-ids/export_alpha_out.txt',
#        '../results/galaxy-ids/export_beta_out.txt',
#        '../results/div-metrics/alpha_diversity.tsv',
#        '../results/div-metrics/beta_diversity.tsv'
        '../results/div-metrics/alpha_heatmap.png',
        '../results/div-metrics/beta_dendro.png',
        '../results/div-metrics/beta_pcoa.png'


rule paste_manifest:
    input:
        '../data'
    output:
        temp('../data/4854_manifest.csv'),
        temp('../results/galaxy-ids/paste_manifest_out.txt')
    log:
        '../results/logs/paste_manifest.log'
    script:
        '../bin/paste_and_manifest.py'

rule get_tool_names:
    input:
        'tools.txt'
    output:
        temp('../results/galaxy-ids/import_tool.txt'),
        temp('../results/galaxy-ids/dada2_tool.txt'),
        temp('../results/galaxy-ids/mafft-raxml_tool.txt'),
        temp('../results/galaxy-ids/rarefy_tool.txt'),
        temp('../results/galaxy-ids/alpha-phylogenetic_tool.txt'),
        temp('../results/galaxy-ids/beta-phylogenetic_tool.txt'),
        temp('../results/galaxy-ids/export_tool.txt')
    log:
       	'../results/logs/get_tool_names.log'
    script:
       	'../bin/get_tool_names.py'

rule qiime2_import:
    input:
        '../results/galaxy-ids/import_tool.txt',
        '../results/galaxy-ids/paste_manifest_out.txt'
    output:
        temp('../results/galaxy-ids/import_out.txt')
    log:
        '../results/logs/import.log'
    script:
        '../bin/run_tools.py'

rule dada2:
    input:
        '../results/galaxy-ids/dada2_tool.txt',
        '../results/galaxy-ids/import_out.txt'
    output:
        temp('../results/galaxy-ids/dada2_out.txt'),
        temp('../results/galaxy-ids/dada2_out2.txt'),
        temp('../results/galaxy-ids/dada2_out3.txt')
    log:
        '../results/logs/dada2.log'
    script:
        '../bin/run_tools.py'

rule mafft_raxml:
    input:
        '../results/galaxy-ids/mafft-raxml_tool.txt',
        '../results/galaxy-ids/dada2_out2.txt'
    output:
        temp('../results/galaxy-ids/mafft-raxml_out.txt'),
        temp('../results/galaxy-ids/mafft-raxml_out2.txt'),
        temp('../results/galaxy-ids/mafft-raxml_out3.txt'),
        temp('../results/galaxy-ids/mafft-raxml_out4.txt')
    log:
        '../results/logs/mafft-raxml.log'
    script:
        '../bin/run_tools.py'

rule rarefy:
    input:
        '../results/galaxy-ids/rarefy_tool.txt',
        '../results/galaxy-ids/dada2_out3.txt'
    output:
        temp('../results/galaxy-ids/rarefy_out.txt')
    log:
        '../results/logs/rarefy.log'
    script:
        '../bin/run_tools.py'

rule alpha_div:
    input:
        '../results/galaxy-ids/alpha-phylogenetic_tool.txt',
        '../results/galaxy-ids/rarefy_out.txt',
        '../results/galaxy-ids/mafft-raxml_out4.txt'
    output:
        temp('../results/galaxy-ids/alpha_div_out.txt')
    log:
        '../results/logs/alpha_div.log'
    script:
        '../bin/run_tools.py'

rule beta_div:
    input:
        '../results/galaxy-ids/beta-phylogenetic_tool.txt',
        '../results/galaxy-ids/rarefy_out.txt',
        '../results/galaxy-ids/mafft-raxml_out4.txt'
    output:
        temp('../results/galaxy-ids/beta_div_out.txt')
    log:
        '../results/logs/beta_div.log'
    script:
        '../bin/run_tools.py'

rule qiime2_export_alpha:
    input:
        '../results/galaxy-ids/export_tool.txt',
        '../results/galaxy-ids/alpha_div_out.txt'
    output:
        temp('../results/galaxy-ids/export_alpha_out.txt')
    log:
        '../results/logs/export_alpha.log'
    script:
        '../bin/run_tools.py'

rule qiime2_export_beta:
    input:
        '../results/galaxy-ids/export_tool.txt',
        '../results/galaxy-ids/beta_div_out.txt'
    output:
        temp('../results/galaxy-ids/export_beta_out.txt')
    log:
        '../results/logs/export_beta.log'
    script:
        '../bin/run_tools.py'

rule extract_data:
    input:
        '../results/galaxy-ids/export_alpha_out.txt',
        '../results/galaxy-ids/export_beta_out.txt'
    output:
        '../results/div-metrics/alpha_diversity.tsv',
        '../results/div-metrics/beta_diversity.tsv'
    log:
        '../results/logs/extract.log'
    script:
        '../bin/galaxy_extract.py'

rule visualize:
    input:
        alpha = '../results/div-metrics/alpha_diversity.tsv',
        beta = '../results/div-metrics/beta_diversity.tsv'
    output:
        heatmap = '../results/div-metrics/alpha_heatmap.png',
        dendro = '../results/div-metrics/beta_dendro.png',
        pcoa = '../results/div-metrics/beta_pcoa.png'
    shell:
        'Rscript ../bin/visualize.R {input.alpha} {input.beta} {output.heatmap} {output.dendro} {output.pcoa}'
